CHANGELOG.md, index.js, package.json
I found that the js-base64 library would occasionally produce invalid base64 output from my images. The output was valid base64, but the resulting decoded image was invalid. I had trouble with this image in particular:
The following is a reproduction of that bug:
```javascript
var fs = require("fs")
var path = require("path")
var base64 = require("js-base64").Base64
var file = fs.readFileSync("test.png")
console.log(base64.encode(file))
// logs incorrect, invalid image: 77+9UE5HDQoaCgAAAA1JSERSAAADDAAAAAEIAwAAAETvv73v...
console.log(file.toString("base64"))
// logs correct, valid image: iVBORw0KGgoAAAANSUhEUgAAAwwAAAABCAMAAABE19kKAA...
```
My pull request uses the native Node file.toString('base64'). This shouldn't affect any portability because, as I understand it, postcss processors are …
=> Fix incorrect base64 output by removing js-base64 dependency.

index.js, test/fixtures/cant-inline-hash.css, test/fixtures/cant-inline-hash.expected.css, test/index.js
Some url()'s have hashes, ignore them. Example: http://css-tricks.com/svg-fragment-identifiers-work/
=> Ignore urls with fragments/hashes

index.js
=> Ignore URLs with hashes only if they need to be inlined

README.md, index.js, test/index.js
Hello!
I'm trying to use your module with custom `url()` function, but I figured out you don't pass `to`, `from` and some other params to custom function
I fixed it.
=> Make custom mode usage possible

index.js, test/fixtures/inline-fallback-function.css, test/fixtures/inline-fallback-function.expected.css, test/index.js
It seems that the call of `processCustom` in `processFallback` does not respect the signature
=> bugfix:inline fallback function does not work

index.js, test/fixtures/copy-hash-parameters.css, test/fixtures/copy-parameters.css, test/index.js
I was trying to use cssnext to inline (fallback copy) assets and using the fontawesome font.
The first commit fixes the issue that it was trying to `fs.existsSync()` the file including the querystring, which ofc does not exist so it was not copying assets as expected.
The second commit was when I added `useHash`, because `path.extname` gets confused by dots inside the querystring, so it was adding the wrong extension `.0`.
With these fixes, it should now correctly copy and rename (hash) the filenames of fontawesome.
=> Inline fallback query

index.js
The three commits in this PR collectively fix the functioning of postcss-url with the {url: "copy"} option when run on Windows.
As a result, this allows npm test to run successfully on Windows.
This PR supersedes #49, #50, and #51. I'll close those.
=> Fix {url: "copy"} on Windows (#35, #47, #48)

src/index.js
The options were being checked for a function `url` option before the options were being matched.  This prevented custom functions from being processed properly when used within an array of options.
=> match options before analyzing

src/index.js, src/type/copy.js, src/type/inline.js, test/misc/messages.js
This adds support for postcss's dependency messaging and allows postcss runners that support file watching to account for any inlined or copied files.
=> add dependency message support

README.md, src/type/inline.js
Adds an `inline` action option to ignore the SVG fragment warning.
When the `maxSize` option is used, some users may wish to avoid the warnings.
=> support ignoring SVG fragment inlining warning

README.md, src/type/inline.js, test/fixtures/can-inline-hash-include.css, test/fixtures/can-inline-hash-include.expected.css, test/fixtures/can-inline-hash.expected.css, test/type/inline.js
A data URI containing a fragment identifier (_hash_) is only fully support in Firefox.  Both webkit and blink based browsers do not support the usage.  See here for additional details: https://bugs.chromium.org/p/chromium/issues/detail?id=123004
This adds an additional `inline` action option to control the addition of the fragment identifier.  It is disabled by default due it its unsupported nature in most browsers.
**Note:** This is a breaking change.
=> add option to include fragment identifiers on inline data URIs

src/type/inline.js, test/fixtures/inline-svg-with-parens.css, test/fixtures/inline-svg-with-parens.expected.css, test/fixtures/svg-with-parens.svg, test/type/inline.js
`(` and `)` are not encoded in default SVG encoding mode(encodeURIComponent).
This cause error in CSS.
wrong output example:
```css
body {
background: url(data:image/svg+xml,%3Csvg%3E%3Cg transform%3D%22translate(0)%22%2F%3E%3C%2Fsvg%3E);
}
```
Wrap url by quotes.
This PR solves #78.
=> Fix wrong encoding

README.md, src/lib/hash.js, src/type/copy.js, test/type/copy.js
useful for later referencing of images (so one can map the compiled images to the original ones)
to activate it simply use this `hashOptions`config:
```js
{
append: true
}
```
=> prepend original filename in hashed filename

src/lib/decl-processor.js, src/lib/paths.js, src/type/copy.js, test/fixtures/skip-urls-with-tilde.css, test/fixtures/skip-urls-with-tilde.expected.css, test/type/copy.js, test/type/inline.js, test/type/rebase.js
Hi!
Webpack has cool feature to determine import from node_modules in stylesheets. Such imports are starting with tilde `~` and should not be processed by this plugin. This PR introduce ability to skip such imports. Corresponding tests are added.
=> Skip URLs starting with tilde

src/index.js, src/lib/decl-processor.js, src/lib/get-file.js, src/type/copy.js, src/type/custom.js, src/type/inline.js, src/type/rebase.js, test/lib/get-file.js, test/misc/messages.js, test/setup.js, test/type/copy.js, test/type/inline.js, test/type/rebase.js
* Replace all sync operations to async
=> Promise for everything

src/lib/paths.js, test/lib/paths.js
If you want to run post-css on the following arrangement:
`postcss app/app.css -o app/app.bundle.css`
Postcss-url will then save the copied assets to `process.cwd()`, which in this case is `.`.  Not correct. It should copy the assets to `./app/${assetsPath}`.  
This fix makes it so the assets are correctly copied to the same folder (presumably inside of a `assetsPath`) when a `to` option exists.   Otherwise, use the old cwd() behavior. 
I'm not 100% sure what the intention of the original logic was, but it appeared to be guarding for when there was a missing `to` option.  This will still preserve the original behavior when `to` is !existy and use process.cwd().  Apologies if this understanding is incorrect.
=> Correct path resolution when to/from paths match

.gitignore, README.md, package-lock.json, package.json, src/index.js, test/setup.js
=> Add support for PostCSS 8

package-lock.json, package.json, src/type/copy.js
make-dir gives a nice promise-based API and is a very lightweight package
=> Replace mkdirp with make-dir

package-lock.json, package.json
As a side effect of a8b6348c7ba2cbe3f76a001be5e8682384769ef7 some dependency versions were effectively downgraded.
=> Update mime and xxhashjs dependencies to their newest version

package-lock.json, package.json
Using the [tilde operator](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1), patch versions will be permitted but minor updates won't be.
Partially solves #145.
I think the tilde operator is a good compromise between the stability of exact versions and semver trust of dependencies. This is particularly relevant for `mime` which gets updated for new types occasingly. IMO it's not worth duplicating the library because of that.
=> Use the tilde operator for dependencies to allow for newer patch version

.npmrc, package.json
This got accidentally reverted when merging #156.
I also changed the `save-prefix` to make sure the tilde is used when manipulating things via the CLI.
=> Fix: upgrade mime to version 2.5
